### ISSUE TITLE
Hi Hat crashes because of SocketException

### ISSUE THREAD

**Issue by josefhuelk** [MV10/monkey-hi-hat#1]
Hello, on first install, Hi Hat launched. Directly after restarting my pc it crashes instantly.
Log (translated):

```
2024-01-28 13:14:45.922 +01:00 [ERR] [CommandLineSwitchPipe 2024-01-28 13:14:45.9180]: Exception SocketException:  Normally, each socket address (protocol, network address or connection) may only be used once.
2024-01-28 13:14:45.930 +01:00 [ERR] [CommandLineSwitchPipe 2024-01-28 13:14:45.9298]:    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at CommandLineSwitchPipe.CommandLineSwitchServer.StartTCPServer(Func`2 switchHandler, CancellationToken cancellationToken, Int32 port)
2024-01-28 13:14:45.930 +01:00 [FTL] [CommandLineSwitchPipe 2024-01-28 13:14:45.9302]: Switch server forcibly terminating process in StartTCPServer
```

**Comment by MV10** [comment]
Hi, thanks for the report. By default, the program uses port 50001, which is controlled by the `UnsecuredPort` setting in the config file `c:\program files\mhh\mhh.conf`, which is a plain text file.

The port is for communication with the Monkey Droid remote control program. If you aren't using that, you can simply change that value to 0 which disables TCP/IP support. It sounds like something else on your system uses port 50001, maybe just at startup. If you plan to use Monkey Droid, you can change that setting to a different port. Port numbers 49152 through 65535 are "dynamic" which means they aren't reserved for things like mail or FTP.

You can see what ports are being used and by which applications with the `netstat -b -a -o | more` command. 

(Note there is also an `UnsecuredRelayPort` in the config file ... that's used by the optional relay service, which can start the visualizer if it isn't running. That isn't relevant to the error you noted, the visualizer program itself doesn't use that value.)

**Comment by josefhuelk** [comment]
Thanks for your quick reply.
I checked the netstat tool and couldn't find any program running on 50001. `Get-NetTCPConnection -LocalPort 50001`  in PowerShell didn't find anything either (other binded ports were found).
I have also tried launching it with five different random ports in the UnsecuredPort configuration within the dynamic port range and received the same error.

**Comment by MV10** [comment]
Strange. Not that I want to resort to _"it works on my machine"_ 😆 but I have it running with TCP listeners on three completely different Win11 desktop setups, one Win10 laptop, formerly on a Raspberry Pi 4B, and on a WSL2 Debian 11 image, and haven't seen any problems.

It runs ok if you disable TCP (set the port number to zero)?

**Comment by josefhuelk** [comment]
Don't worry, there is like something wrong on my end. 
When I switch the port to 0 I get the same error.

**Comment by MV10** [comment]
That's odd. I'll give it some thought, but if you figure it out, please let me know.

If you're a .NET dev, you could mess around with the demo and tcpargs programs in my [CommandLineSwitchPipe](https://github.com/MV10/CommandLineSwitchPipe) repo, which is what this program is using. Or if not, later I can compile and zip them for you to try -- you could just drop the EXEs in the same directory. 

I'm very curious what's behind this!

**Comment by josefhuelk** [comment]
Sorry, I don't have any experience with .NET 
If anyone else starts to have the same issue, it might be worth further investigation, but I will close it for now.
